
STANDARD_ARENA_CELL_SIZE = 2000
STANDARD_ARENA_BORDER_SIZE = 50


ELEMENT_SIZE = 25

ELEMENTS_IN_SUB_CELL = 40  # its means 40 * 40 elements in subcell
SUB_CELL_SIZE = STANDARD_ARENA_CELL_SIZE // (ELEMENTS_IN_SUB_CELL * ELEMENT_SIZE)
