from settings.screen_size import GAME_SCALE
STANDARD_ARENA_CELL_SIZE = int(2000 * GAME_SCALE)
STANDARD_ARENA_BORDER_SIZE = int(50*GAME_SCALE)


ELEMENT_SIZE = int(30*GAME_SCALE)

ELEMENTS_IN_SUB_CELL = 3
SUB_CELL_SIZE = ELEMENT_SIZE // ELEMENTS_IN_SUB_CELL
