CELL_PICTURE_SIZE = 20
WORLD_ARENA_PICTURE_SIZE = [1000, 1000]

WORLD_LINES = WORLD_ARENA_PICTURE_SIZE[1] / CELL_PICTURE_SIZE
WORLD_COLUMS = WORLD_ARENA_PICTURE_SIZE[0] / CELL_PICTURE_SIZE

if WORLD_ARENA_PICTURE_SIZE[0] % CELL_PICTURE_SIZE or WORLD_ARENA_PICTURE_SIZE[1] % CELL_PICTURE_SIZE:
    raise Exception('Wrong CELL or World_Arena pictures size')
