#from settings.screen_size import X_SCALE, Y_SCALE
X_SCALE, Y_SCALE = 1, 1
DEFAULT_BUTTON_X_SIZE = int(150 * X_SCALE)
DEFAULT_BUTTON_HALF_X_SIZE = DEFAULT_BUTTON_X_SIZE // 2
DEFAULT_BUTTON_Y_SIZE = int(50 * Y_SCALE)
DEFAULT_BUTTON_HALF_Y_SIZE = DEFAULT_BUTTON_Y_SIZE // 2
DEFAULT_CLICK_DELAY = 0.5  # seconds
DEFAULT_BORDER_WIDTH = 5
CLICK_ANIMATION_DURATION = 0.5