DEFAULT_BUTTON_X_SIZE = 150
DEFAULT_BUTTON_HALF_X_SIZE = DEFAULT_BUTTON_X_SIZE // 2
DEFAULT_BUTTON_Y_SIZE = 50
DEFAULT_BUTTON_HALF_Y_SIZE = DEFAULT_BUTTON_Y_SIZE // 2
DEFAULT_CLICK_DELAY = 0.5  # seconds
DEFAULT_BORDER_WIDTH = 5
CLICK_ANIMATION_DURATION = 0.5